In [1]:
import pandas as pd

In [2]:
df=pd.read_excel(r'C:/Users/KEVIN/Downloads/e22v1bog_nombres (3).xlsx')

In [3]:
df_filtrado = df[['Nombre de localidad', 'Votos Oviedo', 'Votos Galán']]

In [4]:
df_filtrado['Votos total localidad Oviedo'] = (
    df_filtrado.groupby('Nombre de localidad')['Votos Oviedo']
    .transform('sum')
)

df_filtrado['Votos total localidad Galán'] = (
    df_filtrado.groupby('Nombre de localidad')['Votos Galán']
    .transform('sum')
)

C:\Users\KEVIN\AppData\Local\Temp\ipykernel_12508\532137078.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado['Votos total localidad Oviedo'] = (
C:\Users\KEVIN\AppData\Local\Temp\ipykernel_12508\532137078.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado['Votos total localidad Galán'] = (

In [6]:
df_resumen = (
    df_filtrado
    .groupby('Nombre de localidad', as_index=False)
    .agg({
        'Votos Oviedo': 'sum',
        'Votos Galán': 'sum'
    })
)

In [7]:
df_filtrado

,Nombre de localidad,Votos Oviedo,Votos Galán,Votos total localidad Oviedo,Votos total localidad Galán
0,Usaquén,1910,5894,52921,145778
1,Usaquén,1806,7137,52921,145778
2,Usaquén,1225,2825,52921,145778
3,Usaquén,1422,4302,52921,145778
4,Usaquén,1058,2991,52921,145778
...,...,...,...,...,...
888,Ciudad Bolívar,279,615,28408,85263
889,Ciudad Bolívar,138,459,28408,85263
890,Kennedy,328,854,76624,174421
891,Kennedy,165,366,76624,174421
892,Kennedy,46,61,76624,174421

In [8]:
df_resumen = (
    df
    .groupby(['Nombre de localidad', 'Nombre del sitio'], as_index=False)
    .agg({
        'Votos Oviedo': 'sum',
        'Votos Galán': 'sum'
    })
)

In [9]:
df_resumen

,Nombre de localidad,Nombre del sitio,Votos Oviedo,Votos Galán
0,Antonio Nariño,Casa Comunal Ciudad Jardín,266,504
1,Antonio Nariño,Cinco de Noviembre,129,347
2,Antonio Nariño,Ciudad Berna,704,1533
3,Antonio Nariño,Ciudad Jardín,1002,2644
4,Antonio Nariño,Colegio Adventista Emmanuel,89,215
...,...,...,...,...
888,Usme,Uval - Puerta al Llano,191,704
889,Usme,Valles de Cafam,579,1395
890,Usme,Villa Alemania,169,484
891,Usme,Villa Hermosa,365,1745
892,Usme,Vía al llano,34,95

In [14]:
df_puestos['Total localidad Oviedo'] = (
    df_puestos.groupby('Nombre de localidad')['Votos Oviedo']
    .transform('sum')
)

df_puestos['Total localidad Galán'] = (
    df_puestos.groupby('Nombre de localidad')['Votos Galán']
    .transform('sum')
)

In [15]:
df_puestos

,Nombre de localidad,Nombre del sitio,Votos Oviedo,Votos Galán,Total localidad Oviedo,Total localidad Galán
0,Antonio Nariño,Casa Comunal Ciudad Jardín,266,504,10602,26857
1,Antonio Nariño,Cinco de Noviembre,129,347,10602,26857
2,Antonio Nariño,Ciudad Berna,704,1533,10602,26857
3,Antonio Nariño,Ciudad Jardín,1002,2644,10602,26857
4,Antonio Nariño,Colegio Adventista Emmanuel,89,215,10602,26857
...,...,...,...,...,...,...
888,Usme,Uval - Puerta al Llano,191,704,16006,49509
889,Usme,Valles de Cafam,579,1395,16006,49509
890,Usme,Villa Alemania,169,484,16006,49509
891,Usme,Villa Hermosa,365,1745,16006,49509
892,Usme,Vía al llano,34,95,16006,49509

In [17]:
df_hechos = df_puestos[[
    'Nombre de localidad',
    'Nombre del sitio',
    'Votos Oviedo',
    'Votos Galán'
]]

In [18]:
df_localidades = df_puestos[[
    'Nombre de localidad',
    'Total localidad Oviedo',
    'Total localidad Galán'
]].drop_duplicates()

In [19]:
df_localidades = df_puestos[[
    'Nombre de localidad',
    'Total localidad Oviedo',
    'Total localidad Galán'
]].drop_duplicates()

In [20]:
with pd.ExcelWriter(
    r'C:/Users/KEVIN/Downloads/modelo_elecciones_powerbi.xlsx',
    engine='openpyxl'
) as writer:
    
    df_hechos.to_excel(writer, sheet_name='Hechos_Puestos', index=False)
    df_localidades.to_excel(writer, sheet_name='Dim_Localidades', index=False)